### ISSUE TITLE
Provide rdfs:label labels to entities and classifications

### ISSUE THREAD

**Issue by luigiselmi** [fusepool/patents-reengineering#10]
A rdfs:label must be assigned to entities and classifications to be used instead of their URI in applications.

**Comment by csarven** [comment]
skos:prefLabel is used by default because the entity is of type skos:Concept.

Classifications are created from the CPC scheme in which case a skos:prefLabel is most likely to be present, although not guaranteed. The other possibility for a classification URI to exist is when a patent's classification describes the classification it is patented under. In this case, it only contains skos:notation with respect to labeling in its most general sense.
