### ISSUE TITLE
Duplicate DTD directories

### ISSUE THREAD

**Issue by csarven** [fusepool/patents-reengineering#16]
What's the purpose of:

https://github.com/fusepool/patents-reengineering/tree/master/dtd and
https://github.com/fusepool/patents-reengineering/tree/master/src/main/resources/dtd

when there is:

https://github.com/fusepool/patents-reengineering/tree/master/dtds

**Comment by fifthoffour** [comment]
https://github.com/fusepool/patents-reengineering/tree/master/src/main/resources/dtd 
contains the files used by the enhancer at runtime. Since it is embedded into the jar package for the OSGi bundle, I must follow the maven conventions for such resources.

https://github.com/fusepool/patents-reengineering/tree/master/dtd
This is used by the unit test performed by maven at compilation time.
I've duplicated this folder in order to avoid any possible conflict in case of changes. At this time I think I could remove it.
