### ISSUE TITLE
Don't assign arbitrary http-uri

### ISSUE THREAD

**Issue by retog** [fusepool/patents-reengineering#18]
The assign arbitrary (i.e. http://fusepool.info) HTTP URIs in the te XSLT transformation. To allow dereferenceable HTTP URIs to be assigned by the components that actually run the platform and know about its domain names use ""urn:x-temp:" instead.

**Comment by csarven** [comment]
The URI patterns that's used in XSLTs predates (close to a year) the use of arbitrarily suggested `urn:x-temp` pattern. The URI patterns were also documented and shared with the team. Hence, the HTTP URIs were not arbitrarily assigned, and plenty of time was given for reflection. The use of HTTP URIs was also employed with the consideration of keeping the data Linked Data friendly. If the platform had to factor in variables, they should have been brought up prior to the implementation of `urn:x-temp` in certain areas. This is in contrast to making a change somewhere down the pipeline and expecting rest of the system to adapt while trying to solve a completely different issue.

**Comment by retog** [comment]
The project here is part of an open source platform that should be able to run in different configuration, including intranets not just for the instance run by fusepool. This is also not against HTTP URI it just notes that the assignment is happening ta the wrong place.

**Comment by csarven** [comment]
That idea was integrated in the first commit 
https://github.com/fusepool/patents-reengineering/commit/dfc96101ee70a874737d0e186202e1af1fa7fe0f#diff-413b852ee8885eefafee67cecd11df6bR66 (as part of a config) but was later removed due to a request to make the engine simpler https://github.com/fusepool/patents-reengineering/commit/99f479aa249728acb9aa594614a608d394b22d5b
